name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the stack
      run: docker compose up -d

    # after successful build it takes a while for containers to initialize
    - name: Sleep for __ seconds
      run: sleep 60s
      shell: bash

    - name: 
      run: docker ps -a
